### ISSUE TITLE
添加移动端快速输入方式

### ISSUE THREAD

**Issue by HibernalGlow** [frostime/sy-insert-time#2]
移动端记日记的话也希望能快速输入时间，思源本体对/无法响应。感觉跟调用模板一样缺少快速使用的命令

**Comment by frostime** [comment]
移动端我没怎么用过，简单看了一下似乎是电脑端 `/` 能呼出的东西，在移动端的 `+` 按钮里面没有？
你可以问一下 D 能不能让插件的自定义 `slash` 命令在移动端生效。否则我也想不出有什么特别好的在移动端的交互方式。

**Comment by HibernalGlow** [comment]
https://github.com/siyuan-note/siyuan/issues/10485
老大，加了

**Comment by frostime** [comment]
如果加了的话，这边应该不需要变动什么就能用了。
等思源更新后测试一下吧。

**Comment by HibernalGlow** [comment]
确实能用了，不过还是觉得/方便点

**Comment by HibernalGlow** [comment]
要是能在输入法上面的底栏增加按钮就好了

**Comment by frostime** [comment]
这个就没办法了，既然开发者选择在移动端使用+按钮来替代/，那也不太可能有什么大幅度的变动了。
移动端也没有开发注册额外按钮的接口。

**Comment by frostime** [comment]
说实话在移动端，我觉得不如上输入法干这件事情。
大部分输入法配置一下应该支持直接输入当前的时间的。

**Comment by frostime** [comment]
我先把这个issue关闭了。
后面有什么问题，还可以继续在这个issue下面发帖。

**Comment by HibernalGlow** [comment]
ok，因为我是双拼，打时间会慢一点

**Comment by BoysFight** [comment]
我在Android手机上用docker的siyuan, 好像还是打不出来这个？
