### ISSUE TITLE
最新版本好像用不了啦

### ISSUE THREAD

**Issue by szhiku** [frostime/sy-insert-time#6]
现在/sj /now啥的都不出来啦

**Comment by frostime** [comment]
我这没有发现问题

![image](https://github.com/user-attachments/assets/1cebb894-097a-4b01-b6ff-c8e724c96de5)

请检查一下你插件的设置，看看对应的选项是否正常启用。

![image](https://github.com/user-attachments/assets/7b614ab2-4b2b-4fe6-aeb7-2a55ca9b19fb)

**Comment by frostime** [comment]
没有别的问题先 close了，还有问题就在这里问。
